import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Background from "@/components/Background";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} antialiased text-black dark:text-white scroll-smooth`}
      >
        <ThemeProvider attribute="class">
          {/* <div className="fixed inset-0 z-20 transition dur lg:absolute bg-[radial-gradient(circle_300px_at_90%_200px,rgba(29,78,216,0.15),transparent)]"></div> */}
          <Header />
          <Background />
          <div className="flex mx-auto w-full">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
