import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Background from "@/components/Background";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} antialiased text-black dark:text-white`}
      >
        <ThemeProvider attribute="class">
          <Header />
          <Background />
          <div className="flex mx-auto w-full scroll-smooth">{children}</div>
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
